Update submodule remote urls (#372)
Why? Because https://github.com/gravitational/teleport/ isn't a valid
clone url.

    walt@work:~/git/next$ git clone
    https://github.com/gravitational/teleport/ content/foo
    Cloning into 'content/foo'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.